import Foundation
import WebKit

/// Owns the user's optional YouTube sign-in, persisted as a Netscape cookie
/// file that yt-dlp consumes via its `cookiefile` option.
///
/// YouTube increasingly rejects anonymous downloads with "Sign in to confirm
/// you're not a bot". The app lets the user log in through a `WKWebView`
/// (`YouTubeLoginView`); the resulting session cookies are exported here and
/// passed to `youtube_core` on every probe / search / download.
@MainActor
final class YouTubeAuth: ObservableObject {

    static let shared = YouTubeAuth()

    /// Whether a cookie file is currently on disk. Drives sign-in/out UI.
    @Published private(set) var isSignedIn: Bool

    private init() {
        isSignedIn = FileManager.default.fileExists(atPath: Self.cookieFileURL.path)
    }

    // MARK: - Paths

    /// `<Application Support>/youtube-cookies.txt`. Application Support is
    /// excluded from iCloud/iTunes backup-visible document sharing and is the
    /// right home for app-private credentials.
    private static var cookieFileURL: URL {
        nonisolatedCookieFileURL
    }

    /// Filesystem-only path resolver usable from any actor/thread.
    nonisolated private static var nonisolatedCookieFileURL: URL {
        let base = FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)
            .first ?? FileManager.default.temporaryDirectory
        try? FileManager.default.createDirectory(
            at: base, withIntermediateDirectories: true
        )
        return base.appendingPathComponent("youtube-cookies.txt")
    }

    /// Path to pass to `youtube_core` (empty when not signed in). Safe to call
    /// from any thread/actor — it only touches the filesystem, not published
    /// state — so the Python worker thread can read it directly.
    nonisolated static func currentCookieFilePath() -> String {
        let path = nonisolatedCookieFileURL.path
        return FileManager.default.fileExists(atPath: path) ? path : ""
    }

    // MARK: - Mutations

    /// Persist the supplied cookies as a Netscape cookie file. Only YouTube /
    /// Google cookies are written; anything else is ignored.
    func save(cookies: [HTTPCookie]) {
        let relevant = cookies.filter { Self.isYouTubeCookie($0) }
        guard !relevant.isEmpty else { return }

        let file = Self.netscapeFile(from: relevant)
        do {
            try file.write(to: Self.cookieFileURL, atomically: true, encoding: .utf8)
            isSignedIn = true
        } catch {
            NSLog("[YouTubeAuth] failed to write cookie file: %@", "\(error)")
        }
    }

    /// Remove the stored cookies and clear the WebKit session so a later
    /// sign-in starts fresh.
    func signOut() {
        try? FileManager.default.removeItem(at: Self.cookieFileURL)
        isSignedIn = false

        let store = WKWebsiteDataStore.default()
        store.fetchDataRecords(ofTypes: WKWebsiteDataStore.allWebsiteDataTypes()) { records in
            let targets = records.filter {
                $0.displayName.contains("youtube") || $0.displayName.contains("google")
            }
            store.removeData(
                ofTypes: WKWebsiteDataStore.allWebsiteDataTypes(),
                for: targets
            ) {}
        }
    }

    // MARK: - Helpers

    private static func isYouTubeCookie(_ cookie: HTTPCookie) -> Bool {
        let domain = cookie.domain.lowercased()
        return domain.contains("youtube.com") || domain.contains("google.com")
    }

    /// Serialise cookies into the Netscape `cookies.txt` format yt-dlp expects.
    /// Columns: domain, includeSubdomains, path, secure, expiry, name, value.
    private static func netscapeFile(from cookies: [HTTPCookie]) -> String {
        var lines = [
            "# Netscape HTTP Cookie File",
            "# This file was generated by YouTube Library. Do not edit.",
            "",
        ]
        for cookie in cookies {
            let domain = cookie.domain.hasPrefix(".") ? cookie.domain : ".\(cookie.domain)"
            let includeSub = "TRUE"
            let path = cookie.path.isEmpty ? "/" : cookie.path
            let secure = cookie.isSecure ? "TRUE" : "FALSE"
            // Session cookies have no expiry; yt-dlp accepts 0 for those.
            let expiry = cookie.expiresDate.map { String(Int($0.timeIntervalSince1970)) } ?? "0"
            let name = cookie.name
            let value = cookie.value
            lines.append([domain, includeSub, path, secure, expiry, name, value]
                .joined(separator: "\t"))
        }
        return lines.joined(separator: "\n") + "\n"
    }
}
